require("dotenv").config();

const fs = require("fs");
const path = require("path");
const os = require("os");
const crypto = require("crypto");

const googleTTS = require("google-tts-api");
const ffmpegPath = require("ffmpeg-static");

/*
========================================================
GAVEAI VIDEO AUDIO SERVICE
========================================================

This service is PROVIDER-INDEPENDENT.

It works with videos generated by:

- WaveSpeedAI
- Replicate
- Hugging Face
- ZeroGPU
- Any future GaveAI video provider

FLOW:

Video Provider
      ↓
Generated MP4
      ↓
Extract spoken dialogue from prompt
      ↓
Detect / select language
      ↓
Google TTS
      ↓
MP3 voice
      ↓
FFmpeg
      ↓
Final MP4 with voice
      ↓
ImageKit

The final MP4 contains the audio track.

========================================================
*/

/*
========================================================
CONFIGURATION
========================================================
*/

const DEFAULT_LANGUAGE =
  process.env.GAVEAI_DEFAULT_TTS_LANGUAGE || "en";

const DEFAULT_SPEAKING_RATE =
  Number(
    process.env.GAVEAI_TTS_SPEAKING_RATE
  ) || 1;

const TTS_TIMEOUT =
  Number(
    process.env.GAVEAI_TTS_TIMEOUT_MS
  ) || 120000;

/*
========================================================
HELPER: CLEAN STRING
========================================================
*/

function cleanString(value) {
  if (typeof value !== "string") {
    return "";
  }

  return value.trim();
}

/*
========================================================
HELPER: SLEEP
========================================================
*/

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

/*
========================================================
HELPER: VALID FILE
========================================================
*/

function validateVideoFile(videoFile) {
  if (!videoFile) {
    throw new Error(
      "Video file path is missing."
    );
  }

  if (!fs.existsSync(videoFile)) {
    throw new Error(
      `Video file does not exist: ${videoFile}`
    );
  }

  const stats =
    fs.statSync(videoFile);

  if (!stats.isFile()) {
    throw new Error(
      "Generated video path is not a file."
    );
  }

  if (stats.size <= 0) {
    throw new Error(
      "Generated video file is empty."
    );
  }

  return true;
}

/*
========================================================
LANGUAGE MAP
========================================================

Google TTS language codes.

This allows GaveAI to support many languages.

========================================================
*/

const LANGUAGE_ALIASES = {
  english: "en",
  en: "en",

  french: "fr",
  français: "fr",
  francais: "fr",
  fr: "fr",

  haitian: "ht",
  "haitian creole": "ht",
  "kreyol ayisyen": "ht",
  "kreyòl ayisyen": "ht",
  creole: "ht",
  créole: "ht",
  ht: "ht",

  spanish: "es",
  español: "es",
  espanol: "es",
  es: "es",

  portuguese: "pt",
  português: "pt",
  portugues: "pt",
  pt: "pt",

  german: "de",
  deutsch: "de",
  de: "de",

  italian: "it",
  italiano: "it",
  it: "it",

  dutch: "nl",
  nederlands: "nl",
  nl: "nl",

  russian: "ru",
  русский: "ru",
  ru: "ru",

  ukrainian: "uk",
  українська: "uk",
  uk: "uk",

  arabic: "ar",
  العربية: "ar",
  ar: "ar",

  hindi: "hi",
  हिन्दी: "hi",
  hi: "hi",

  bengali: "bn",
  বাংলা: "bn",
  bn: "bn",

  chinese: "zh",
  mandarin: "zh-CN",
  中文: "zh-CN",
  "zh-cn": "zh-CN",
  "zh-tw": "zh-TW",

  japanese: "ja",
  日本語: "ja",
  ja: "ja",

  korean: "ko",
  한국어: "ko",
  ko: "ko",

  vietnamese: "vi",
  tiếng việt: "vi",
  vi: "vi",

  thai: "th",
  ไทย: "th",
  th: "th",

  turkish: "tr",
  türkçe: "tr",
  turkce: "tr",
  tr: "tr",

  polish: "pl",
  polski: "pl",
  pl: "pl",

  romanian: "ro",
  română: "ro",
  romana: "ro",
  ro: "ro",

  czech: "cs",
  čeština: "cs",
  cestina: "cs",
  cs: "cs",

  greek: "el",
  ελληνικά: "el",
  el: "el",

  swedish: "sv",
  svenska: "sv",
  sv: "sv",

  danish: "da",
  dansk: "da",
  da: "da",

  norwegian: "no",
  norsk: "no",
  no: "no",

  finnish: "fi",
  suomi: "fi",
  fi: "fi",

  hebrew: "he",
  עברית: "he",
  he: "he",

  indonesian: "id",
  bahasa: "id",
  indonesia: "id",
  id: "id",

  malay: "ms",
  melayu: "ms",
  ms: "ms",

  filipino: "fil",
  tagalog: "fil",
  fil: "fil",

  swahili: "sw",
  kiswahili: "sw",
  sw: "sw",

  tamil: "ta",
  தமிழ்: "ta",
  ta: "ta",

  telugu: "te",
  తెలుగు: "te",
  te: "te",

  marathi: "mr",
  मराठी: "mr",
  mr: "mr",

  gujarati: "gu",
  ગુજરાતી: "gu",
  gu: "gu",

  kannada: "kn",
  ಕನ್ನಡ: "kn",
  kn: "kn",

  malayalam: "ml",
  മലയാളം: "ml",
  ml: "ml"
};

/*
========================================================
NORMALIZE LANGUAGE
========================================================
*/

function normalizeLanguage(language) {
  const value =
    cleanString(language)
      .toLowerCase();

  if (!value) {
    return DEFAULT_LANGUAGE;
  }

  if (
    LANGUAGE_ALIASES[value]
  ) {
    return LANGUAGE_ALIASES[value];
  }

  /*
  ------------------------------------------------------
  Direct language code
  ------------------------------------------------------
  */

  if (
    /^[a-z]{2}$/i.test(value)
  ) {
    return value;
  }

  /*
  ------------------------------------------------------
  Regional code
  ------------------------------------------------------
  */

  if (
    /^[a-z]{2}-[a-z]{2}$/i.test(value)
  ) {
    return value;
  }

  return DEFAULT_LANGUAGE;
}

/*
========================================================
LANGUAGE DETECTION
========================================================

This is a lightweight fallback.

The frontend should ideally send:

language: "fr"

or:

language: "ht"

or:

language: "en"

When language is not provided, we inspect
the text for common language patterns.

========================================================
*/

function detectLanguageFromText(text) {
  const value =
    cleanString(text)
      .toLowerCase();

  if (!value) {
    return DEFAULT_LANGUAGE;
  }

  /*
  Haitian Creole
  */

  const haitianWords = [
    "mwen",
    "ou",
    "li",
    "nou",
    "yo",
    "fè",
    "fe",
    "epi",
    "pou",
    "nan",
    "ak",
    "yon",
    "bonjou",
    "bonswa",
    "mesi",
    "kijan",
    "mwen vle",
    "tanpri",
    "kote",
    "pa gen"
  ];

  const frenchWords = [
    "bonjour",
    "bonsoir",
    "merci",
    "je",
    "tu",
    "vous",
    "nous",
    "avec",
    "pour",
    "une",
    "un",
    "dans",
    "est",
    "faire",
    "dit"
  ];

  const spanishWords = [
    "hola",
    "buenos",
    "gracias",
    "yo",
    "tú",
    "usted",
    "para",
    "con",
    "una",
    "uno",
    "que",
    "es"
  ];

  const portugueseWords = [
    "olá",
    "obrigado",
    "obrigada",
    "eu",
    "você",
    "para",
    "com",
    "uma",
    "que",
    "não"
  ];

  const germanWords = [
    "hallo",
    "danke",
    "ich",
    "du",
    "sie",
    "und",
    "für",
    "mit",
    "nicht",
    "ist"
  ];

  const italianWords = [
    "ciao",
    "grazie",
    "io",
    "tu",
    "lei",
    "con",
    "per",
    "una",
    "che",
    "non"
  ];

  function score(words) {
    return words.reduce(
      (total, word) => {
        return (
          total +
          (
            value.includes(
              ` ${word} `
            ) ||
            value.startsWith(
              `${word} `
            ) ||
            value.endsWith(
              ` ${word}`
            )
              ? 1
              : 0
          )
        );
      },
      0
    );
  }

  const scores = {
    ht: score(haitianWords),
    fr: score(frenchWords),
    es: score(spanishWords),
    pt: score(portugueseWords),
    de: score(germanWords),
    it: score(italianWords)
  };

  let bestLanguage =
    DEFAULT_LANGUAGE;

  let bestScore = 0;

  for (
    const [language, languageScore]
      of Object.entries(scores)
  ) {
    if (
      languageScore >
      bestScore
    ) {
      bestScore =
        languageScore;

      bestLanguage =
        language;
    }
  }

  return bestLanguage;
}

/*
========================================================
EXTRACT SPOKEN DIALOGUE
========================================================

Examples:

"Create a chicken and make it say Bonjour"

→ Bonjour

"Make a man say: Hello, how are you?"

→ Hello, how are you?

"Fè yon kok epi fè li di bonjou"

→ bonjou

"Create a woman saying 'I love this city'"

→ I love this city

If no dialogue can be extracted, we return
an empty string.

========================================================
*/

function extractDialogue(prompt) {
  const text =
    cleanString(prompt);

  if (!text) {
    return "";
  }

  /*
  ------------------------------------------------------
  Quoted text
  ------------------------------------------------------
  */

  const quotedPatterns = [
    /"([^"]+)"/,
    /'([^']+)'/,
    /“([^”]+)”/,
    /‘([^’]+)’/
  ];

  for (
    const pattern
      of quotedPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      );
    }
  }

  /*
  ------------------------------------------------------
  English
  ------------------------------------------------------
  */

  const englishPatterns = [
    /\bsay(?:s|ing)?\s*[:\-]?\s*(.+)$/i,
    /\bsays?\s*[:\-]?\s*(.+)$/i,
    /\bspeaks?\s*[:\-]?\s*(.+)$/i,
    /\bmake\s+[^.]*?\bsay\s+(.+)$/i,
    /\blet\s+[^.]*?\bsay\s+(.+)$/i
  ];

  for (
    const pattern
      of englishPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      )
        .replace(/[.!?]+$/, "")
        .trim();
    }
  }

  /*
  ------------------------------------------------------
  French
  ------------------------------------------------------
  */

  const frenchPatterns = [
    /\bdit(?:e|es)?\s*[:\-]?\s*(.+)$/i,
    /\bdire\s*[:\-]?\s*(.+)$/i,
    /\bdisant\s*[:\-]?\s*(.+)$/i,
    /\bfaire\s+[^.]*?\bdire\s+(.+)$/i
  ];

  for (
    const pattern
      of frenchPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      )
        .replace(/[.!?]+$/, "")
        .trim();
    }
  }

  /*
  ------------------------------------------------------
  Haitian Creole
  ------------------------------------------------------
  */

  const haitianPatterns = [
    /\bdi\s*[:\-]?\s*(.+)$/i,
    /\bdiy\s*[:\-]?\s*(.+)$/i,
    /\bfè\s+[^.]*?\bdi\s+(.+)$/i,
    /\bfe\s+[^.]*?\bdi\s+(.+)$/i,
    /\bli\s+di\s+(.+)$/i
  ];

  for (
    const pattern
      of haitianPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      )
        .replace(/[.!?]+$/, "")
        .trim();
    }
  }

  /*
  ------------------------------------------------------
  Spanish
  ------------------------------------------------------
  */

  const spanishPatterns = [
    /\bdecir\s*[:\-]?\s*(.+)$/i,
    /\bdice\s*[:\-]?\s*(.+)$/i,
    /\bdiciendo\s*[:\-]?\s*(.+)$/i
  ];

  for (
    const pattern
      of spanishPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      )
        .replace(/[.!?]+$/, "")
        .trim();
    }
  }

  /*
  ------------------------------------------------------
  If the whole prompt looks like dialogue,
  allow it to become speech.

  ------------------------------------------------------
  */

  const directSpeechPatterns = [
    /^say\s+(.+)$/i,
    /^saying\s+(.+)$/i,
    /^dit\s+(.+)$/i,
    /^di\s+(.+)$/i,
    /^dis\s+(.+)$/i,
    /^decir\s+(.+)$/i
  ];

  for (
    const pattern
      of directSpeechPatterns
  ) {
    const match =
      text.match(pattern);

    if (
      match &&
      match[1]
    ) {
      return cleanString(
        match[1]
      );
    }
  }

  return "";
}

/*
========================================================
CREATE TTS AUDIO
========================================================
*/

async function createTTSAudio({
  text,
  language,
  slow
}) {
  const spokenText =
    cleanString(text);

  if (!spokenText) {
    throw new Error(
      "TTS text is empty."
    );
  }

  const normalizedLanguage =
    normalizeLanguage(
      language
    );

  console.log(
    "========================================"
  );

  console.log(
    "GAVEAI TTS STARTED"
  );

  console.log(
    "LANGUAGE:",
    normalizedLanguage
  );

  console.log(
    "TEXT:",
    spokenText
  );

  console.log(
    "========================================"
  );

  const audioUrl =
    googleTTS.getAudioUrl(
      spokenText,
      {
        lang:
          normalizedLanguage,

        slow:
          Boolean(slow),

        host:
          "https://translate.google.com"
      }
    );

  if (!audioUrl) {
    throw new Error(
      "Google TTS did not return an audio URL."
    );
  }

  const controller =
    new AbortController();

  const timeout =
    setTimeout(() => {
      controller.abort();
    }, TTS_TIMEOUT);

  try {
    const response =
      await fetch(
        audioUrl,
        {
          method: "GET",
          signal:
            controller.signal
        }
      );

    if (!response.ok) {
      throw new Error(
        `TTS audio download failed: HTTP ${response.status}`
      );
    }

    const arrayBuffer =
      await response.arrayBuffer();

    const audioBuffer =
      Buffer.from(
        arrayBuffer
      );

    if (
      audioBuffer.length === 0
    ) {
      throw new Error(
        "TTS audio file is empty."
      );
    }

    const fileName =
      `gaveai-tts-${crypto.randomUUID()}.mp3`;

    const filePath =
      path.join(
        os.tmpdir(),
        fileName
      );

    await fs.promises.writeFile(
      filePath,
      audioBuffer
    );

    console.log(
      "GAVEAI TTS SUCCESS"
    );

    console.log(
      "AUDIO FILE:",
      filePath
    );

    console.log(
      "AUDIO SIZE:",
      audioBuffer.length
    );

    console.log(
      "========================================"
    );

    return {
      filePath,
      fileName,
      size:
        audioBuffer.length,
      language:
        normalizedLanguage,
      text:
        spokenText
    };
  } catch (error) {
    if (
      error?.name ===
      "AbortError"
    ) {
      throw new Error(
        `TTS request timed out after ${TTS_TIMEOUT}ms.`
      );
    }

    throw error;
  } finally {
    clearTimeout(timeout);
  }
}

/*
========================================================
GET VIDEO DURATION
========================================================

We use FFmpeg itself to create the final output.
The easiest provider-independent approach is:

- video continues normally
- voice starts at beginning
- when voice ends, video continues
- no silent/black replacement is added

========================================================
*/

/*
========================================================
MERGE VIDEO + VOICE
========================================================
*/

async function mergeVideoAndVoice({
  videoFile,
  audioFile,
  outputFile
}) {
  validateVideoFile(
    videoFile
  );

  if (!audioFile) {
    throw new Error(
      "Audio file is missing."
    );
  }

  if (!fs.existsSync(audioFile)) {
    throw new Error(
      `Audio file does not exist: ${audioFile}`
    );
  }

  const finalOutput =
    outputFile ||
    path.join(
      os.tmpdir(),
      `gaveai-video-with-voice-${crypto.randomUUID()}.mp4`
    );

  console.log(
    "========================================"
  );

  console.log(
    "FFMPEG AUDIO MERGE STARTED"
  );

  console.log(
    "VIDEO:",
    videoFile
  );

  console.log(
    "AUDIO:",
    audioFile
  );

  console.log(
    "OUTPUT:",
    finalOutput
  );

  console.log(
    "FFMPEG:",
    ffmpegPath
  );

  console.log(
    "========================================"
  );

  await new Promise(
    (resolve, reject) => {
      const { spawn } =
        require("child_process");

      const args = [
        "-y",

        "-i",
        videoFile,

        "-i",
        audioFile,

        /*
        ------------------------------------------------
        VIDEO
        ------------------------------------------------
        */

        "-map",
        "0:v:0",

        /*
        ------------------------------------------------
        AUDIO
        ------------------------------------------------
        */

        "-map",
        "1:a:0",

        /*
        ------------------------------------------------
        VIDEO CODEC
        ------------------------------------------------
        */

        "-c:v",
        "copy",

        /*
        ------------------------------------------------
        AUDIO CODEC
        ------------------------------------------------
        */

        "-c:a",
        "aac",

        "-b:a",
        "192k",

        /*
        ------------------------------------------------
        AUDIO BEHAVIOR
        ------------------------------------------------
        */

        "-shortest",

        /*
        ------------------------------------------------
        MP4 COMPATIBILITY
        ------------------------------------------------
        */

        "-movflags",
        "+faststart",

        finalOutput
      ];

      const process =
        spawn(
          ffmpegPath,
          args,
          {
            windowsHide:
              true
          }
        );

      let stderr = "";

      process.stderr.on(
        "data",
        (data) => {
          stderr +=
            data.toString();
        }
      );

      process.on(
        "error",
        (error) => {
          reject(error);
        }
      );

      process.on(
        "close",
        (code) => {
          if (code !== 0) {
            reject(
              new Error(
                `FFmpeg failed with exit code ${code}: ${stderr.slice(-4000)}`
              )
            );

            return;
          }

          resolve();
        }
      );
    }
  );

  if (
    !fs.existsSync(
      finalOutput
    )
  ) {
    throw new Error(
      "FFmpeg completed but final video file was not created."
    );
  }

  const stats =
    await fs.promises.stat(
      finalOutput
    );

  if (stats.size <= 0) {
    throw new Error(
      "FFmpeg created an empty final video."
    );
  }

  console.log(
    "========================================"
  );

  console.log(
    "FFMPEG AUDIO MERGE SUCCESS"
  );

  console.log(
    "FINAL VIDEO:",
    finalOutput
  );

  console.log(
    "FINAL SIZE:",
    stats.size
  );

  console.log(
    "========================================"
  );

  return {
    filePath:
      finalOutput,

    fileName:
      path.basename(
        finalOutput
      ),

    size:
      stats.size
  };
}

/*
========================================================
CLEAN TEMP FILE
========================================================
*/

function cleanupAudioFile(
  audioFile
) {
  if (!audioFile) {
    return;
  }

  try {
    if (
      fs.existsSync(
        audioFile
      )
    ) {
      fs.unlinkSync(
        audioFile
      );

      console.log(
        "TTS AUDIO DELETED:",
        audioFile
      );
    }
  } catch (error) {
    console.warn(
      "TTS AUDIO CLEANUP WARNING:",
      error.message
    );
  }
}

/*
========================================================
ADD VOICE TO VIDEO
========================================================

This is the main public function.

It accepts a video from ANY provider.

========================================================
*/

async function addVoiceToVideo({
  videoFile,
  prompt,
  voiceText,
  language,
  slow = false,
  enabled = true
}) {
  validateVideoFile(
    videoFile
  );

  /*
  ------------------------------------------------------
  Voice disabled
  ------------------------------------------------------
  */

  if (!enabled) {
    return {
      success: true,
      voiceAdded: false,
      videoFile,
      audioFile: null,
      voiceText: "",
      language:
        normalizeLanguage(
          language
        )
    };
  }

  /*
  ------------------------------------------------------
  Determine spoken text
  ------------------------------------------------------
  */

  let spokenText =
    cleanString(
      voiceText
    );

  if (!spokenText) {
    spokenText =
      extractDialogue(
        prompt
      );
  }

  /*
  ------------------------------------------------------
  No dialogue
  ------------------------------------------------------
  */

  if (!spokenText) {
    console.log(
      "NO SPOKEN DIALOGUE FOUND."
    );

    console.log(
      "VIDEO WILL BE RETURNED WITHOUT ADDED VOICE."
    );

    return {
      success: true,
      voiceAdded: false,
      videoFile,
      audioFile: null,
      voiceText: "",
      language:
        normalizeLanguage(
          language
        )
    };
  }

  /*
  ------------------------------------------------------
  Determine language
  ------------------------------------------------------
  */

  const finalLanguage =
    language
      ? normalizeLanguage(
          language
        )
      : detectLanguageFromText(
          spokenText
        );

  let ttsAudio =
    null;

  let mergedVideo =
    null;

  try {
    /*
    ====================================================
    CREATE VOICE
    ====================================================
    */

    ttsAudio =
      await createTTSAudio({
        text:
          spokenText,

        language:
          finalLanguage,

        slow
      });

    /*
    ====================================================
    MERGE VOICE INTO VIDEO
    ====================================================
    */

    mergedVideo =
      await mergeVideoAndVoice({
        videoFile,

        audioFile:
          ttsAudio.filePath
      });

    /*
    ====================================================
    SUCCESS
    ====================================================
    */

    return {
      success: true,

      voiceAdded: true,

      videoFile:
        mergedVideo.filePath,

      audioFile:
        ttsAudio.filePath,

      voiceText:
        spokenText,

      language:
        finalLanguage,

      fileName:
        mergedVideo.fileName,

      fileSize:
        mergedVideo.size
    };
  } catch (error) {
    console.error(
      "GAVEAI VIDEO AUDIO ERROR:",
      error
    );

    /*
    ----------------------------------------------------
    Cleanup TTS audio
    ----------------------------------------------------
    */

    cleanupAudioFile(
      ttsAudio?.filePath
    );

    throw error;
  }
}

/*
========================================================
PROVIDER-INDEPENDENT POST PROCESSING
========================================================
*/

async function processGeneratedVideo({
  videoFile,
  prompt,
  voiceText,
  language,
  enableVoice = true,
  slowVoice = false
}) {
  if (!videoFile) {
    throw new Error(
      "processGeneratedVideo requires videoFile."
    );
  }

  /*
  ------------------------------------------------------
  Voice disabled
  ------------------------------------------------------
  */

  if (!enableVoice) {
    return {
      success: true,

      voiceAdded: false,

      videoFile,

      voiceText:
        cleanString(
          voiceText
        ),

      language:
        normalizeLanguage(
          language
        )
    };
  }

  const result =
    await addVoiceToVideo({
      videoFile,

      prompt,

      voiceText,

      language,

      slow:
        slowVoice,

      enabled:
        true
    });

  return result;
}

/*
========================================================
HEALTH
========================================================
*/

function getVideoAudioStatus() {
  return {
    configured:
      Boolean(ffmpegPath),

    ttsProvider:
      "Google TTS",

    ffmpeg:
      ffmpegPath
        ? "CONFIGURED"
        : "NOT CONFIGURED",

    defaultLanguage:
      DEFAULT_LANGUAGE,

    speakingRate:
      DEFAULT_SPEAKING_RATE
  };
}

/*
========================================================
EXPORTS
========================================================
*/

module.exports = {
  addVoiceToVideo,
  processGeneratedVideo,
  createTTSAudio,
  mergeVideoAndVoice,
  extractDialogue,
  detectLanguageFromText,
  normalizeLanguage,
  getVideoAudioStatus
};